### ISSUE TITLE
Program crashes constantly

### ISSUE THREAD

**Issue by Manolme** [jorio/OttoMatic#13]
Hey there, 

Everytime I try to play OttoMatic the program crashes after like 2 minutes. I can start to play but it does not take long and the program terminates itself. 

The Terminal says: 

~ % /Applications/Otto\ Matic.app/Contents/MacOS/OttoMatic
KillMacMouseAcceleration: IOHIDGetParameter returned unexpected actualSize! (Got 4)
RestoreMacMouseAcceleration: Acceleration value not tainted (57344).

I've got a macOS Big Sur, Version 11.1.

Thanks for help :)

Best Wishes
Manolme

**Comment by jorio** [comment]
This mouse acceleration error can be fixed by upgrading to 11.5 or later, but I don't think that's causing the crash you're experiencing.

Is it an Intel or Apple Silicon machine? Are you doing anything special in the game to trigger the crash? Is there any other info related to Otto Matic in the Console app?

**Comment by jorio** [comment]
Otto Matic 4.0.1 has some stability fixes. Feel free to reopen the issue if it still crashes for you (with a bit more info ;))
