### ISSUE TITLE
Tractor enemy on Earth can get stuck out of bounds

### ISSUE THREAD

**Issue by InSimpleTermsJordan** [jorio/OttoMatic#15]
The indestructible, one-of-a-kind tractor enemy on Planet Earth: Bentley Farm can sometimes pass through the non-breakable fence walls on the left of the area (opposite side of the destructible gate), preventing progression in the level unless the player either somehow gets the tractor back through the fence to break the correct gate on the other side or bypasses the gate entirely by clipping through a wall
![2022-03-26 17-19-22-227 jkpie TRAVELLINGMEMES OttoMatic 1920x1080](https://user-images.githubusercontent.com/6912435/160263938-d856c7c5-4219-4c13-a5f9-1d0f6d405096.png)

**Comment by 6exagon** [comment]
Not sure about the ports of this game, but the original definitely had this problem too (especially near the small rectangular hay bales on the right of the screen). This might not be a very easy fix, since other stuff can get stuck in walls too.
Also, to get past that room without the tractor, jump-jet onto the large round hay bales next to the gate (a little bit precise but not too hard) and then jump-jet over the gate.

**Comment by jorio** [comment]
Yeah, fence collisions are kinda flaky in several Pangea games and my ports have inherited the issue. I didn't dwell on it too much because the player usually has to go out of their way to go out of bounds.

However, in this case, it's a gameplay-breaking bug that's worth fixing. I'd need to sit down and take a good look at it. PRs welcome if anyone figures out how to strengthen fence collisions before I do.

**Comment by InSimpleTermsJordan** [comment]
I wonder if it would be better to just implement a sort of failsafe for this specific case that just forces the tractor's coordinates to stay within a certain range and snap them back in if it tries to go out, since this is the only instance in the game that I can remember of a non-player entity needing to be lured into the right spot in order to progress normally

**Comment by jorio** [comment]
[Otto Matic 4.0.1](https://github.com/jorio/OttoMatic/releases/tag/4.0.1) stabilizes fence physics and resets the tractor's position when Otto dies. I haven't been able to get the tractor to go out of bounds anymore. It can still get stuck in hay bales but it manages to free itself if you lure it just right. Feel free to reopen the issue if it's still a blocker.
