### ISSUE TITLE
Missing Pair of Teleporters Discovered in Original Aspyr Version; Possible Reimplementation?

### ISSUE THREAD

**Issue by TheBigStinkyBee** [jorio/OttoMatic#20]
Recently I acquired an iMac G4 and to my excitement I discovered it had Otto Matic 1.0 bundled with it, the original Aspyr-published version! But there was an even more exciting discovery that solved an issue I have had with Otto Matic when I played it as a kid.

Some background: When you start on Planet Knarr, you will happen upon a crunch door on the way toward the first zip line. There is one problem though: it is the smooth side, i.e. the side without the rivets, which cannot be activated with Otto's supernova. This crunch door guards a singular room with a Brain Alien and a powerup pod inside. Nothing special. The only way I have managed to get in was to somehow jump-jet on top of a Mutant Robot, then jump-jet from his head onto a crashed flying saucer, then jump-jet over the crunch door. It's a tedious, exploit-y process that reaps little-to-no reward, so I often just ignore it.

I have only ever played later versions of the game so the purpose of this room was always unknown to me. But when playing 1.0, I happened upon a remarkable discovery: in the very last area where your rocket is waiting, there is a teleporter off to the side. This teleporter is very odd, as there appears to be a zipline handle embedded in the ground inside the teleporter. I thought maybe it was just something Brian Greenstone accidentally left there and never got around to cleaning it up. So I decided to give it a Supernova to see if it would turn on, and it did! I walked through it and it brought me to that previously-inaccessible room at the beginning of the level. Interestingly, the Teleporter in this room had a zipline post in the middle. What's going on here? I tried to get screenshots, but Mac OS X 10.1 "Puma" wouldn't take screenshots during gameplay. Only when I got on the rocket and left did it finally do it, which left me with screenshots of the sky.

It seems that in a later version of the game Brian had removed the teleporters for unknown reasons. The darkened, shadowy area where the teleporter stood still remains, though. Is it possible to reimplement them? I've attached an edited version of the map from the strategy guide to show you where these teleporters were.

![knarrmissingteleporters](https://user-images.githubusercontent.com/108010014/179743184-a52bffcf-01b2-47ba-9a40-3e67cddab500.png)

**Comment by orazioedoardo** [comment]
Try to replace `Data/Terrain/Apocalypse.ter` and `Data/Terrain/Apocalypse.ter.rsrc` with the same files from your version.

**Comment by jorio** [comment]
These teleporters were [removed in version 1.0.2](https://github.com/jorio/OttoMatic/blob/48becd8e8edc51c4e55b5b79b4019b859d762dd2/src/Items/Teleporter.c#L99).

Each teleporter comes with a little sign planted in the ground. The sign shows a symbol that identifies a destination point on the map. I'm guessing that they forgot to create specific symbols for this pair of teleporters before the game shipped, so Brian removed those two teleporters altogether in 1.0.2.

The weird zipline stuff that you're seeing in version 1.0.0 are glitches caused by the missing signs. The game is trying to spawn the models for signs #&#8203;12 and #&#8203;13, but they don't exist. Instead, zipline models take up the slots that should have been reserved for the missing signs.

For what it's worth, the teleporter items are still stored in the terrain files as items #&#8203;104 and #&#8203;127. They're just ignored by the code. You can warp to their positions using the warp menu (hold down ~ and F9).

As for adding those two teleporters back, I suppose we could simply spawn them without a sign.

**Comment by foote-darrell** [comment]
I remember seeing that on the packaged version of my iMac G4 running Mac OS X 10.3 Panther. [It also looks like in the first version](https://macintoshgarden.org/games/otto-matic) the powerup gears on the heads-up display were just round saucers or something.

**Comment by foote-darrell** [comment]
I loaded it up on my iMac G4 running Mac OS X 10.3 Panther. Indeed those teleporters load the zipline pole and handles inside. It also seems to catch you when you walk back out making it hard to leave. These are genuine screenshots captured mid-game from the iMac G4.
![Teleporter02](https://user-images.githubusercontent.com/70550621/183786290-c20e441b-3fb3-4fda-9ecd-269eaf1136a1.png)
![Teleporter06](https://user-images.githubusercontent.com/70550621/183786297-a1391ad8-de19-43fc-a10c-502eae8352c6.png)

**Comment by jorio** [comment]
Those teleporters were restored in [Otto Matic 4.0.1](https://github.com/jorio/OttoMatic/releases/tag/4.0.1)!
