### ISSUE TITLE
Change license to Apache 2.0 with common clause?

### ISSUE THREAD

**Issue by jpenguin** [jorio/OttoMatic#6]
I know Brian would also have to approve this, but asking you first

Creative Commons is not recommended for source code https://opensource.stackexchange.com/questions/9242/why-does-creative-commons-recommend-not-using-cc-by-licenses-for-software.  I would consider looking into Apache 2.0 with common clause, like they did at https://redis.com/blog/redis-license-bsd-will-remain-bsd/

The textures, sounds, music, & models could even stay CC, it's common to have assets under a CC license.

The common clause & NC would still keep it out of debian and the official fedora repository, but this would stop using an art license for source code.

**Comment by jorio** [comment]
The ports use Creative Commons NC-BY-SA because I needed a license that covers everything in the game (source code and assets) and prevents third parties from profiting from the game.

Not sure changing picking a different license for the source code is worth the trouble if distros won't host the game in their repositories because the artwork isn't pure FOSS anyway?

**Comment by jpenguin** [comment]
Yeah, it;'s probably not worth it.  With appimage through itch.io & lutris, it really doesn't matter
